# Generated by Django 2.2.12 on 2023-03-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='blogs')),
                ('blog_name', models.CharField(default='', max_length=50)),
                ('blog_date', models.CharField(max_length=50)),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
